# Site settings
title: The Shifting
header-img: img/home-bg.jpg
email: info@theshifting.ca
description: "We shift around Vancouver."
url: "http://test.adriandiaz.ca"
twitter_username: ShiftingCa
github_username:  adriandgr
facebook_username:  TheShifting

# Build settings
markdown: kramdown
highlighter: pygments
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
