# Site settings
title: The Shifting
header-img: img/home-bg.jpg
email: your-email@yourdomain.com
description: "We shift around Vancouver."
baseurl: "http://test.adriandiaz.ca"
url: "http://test.adriandiaz.ca"
twitter_username: adgr72
github_username:  adriandgr
facebook_username:  IronSummitMedia

# Build settings
markdown: kramdown
highlighter: pygments
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
